### ISSUE TITLE
Render time and where is model file?

### ISSUE THREAD

**Issue by Adzido** [another-ai/stable_cascade_easy#10]
Is it normal 1500x1500  render on a 4080 takes about 90 seconds?

Where are models? I saw during the installation of the extension that long files were downloaded, I can't find them in the A1111 folder. 

Thanks.

**Comment by blahouel** [comment]
I am not on windows, but In linux, you can find the models in a hidden folder /home/user/.cache/huggingface/hub/
"user" is your user directory name
