### ISSUE TITLE
Possible to load trained models? (Specifically Stage C 1B)?

### ISSUE THREAD

**Issue by CCpt5** [another-ai/stable_cascade_easy#8]
Hello,

Thanks for the quick/"lite" implementation for inference!

I've been dabbling w/ fine tuning  stage C 1B model and had decent success but at the moment there isn't a simple way for me to test generations after training some.  There's also at least one custom trained model (test) on Civitai: https://civitai.com/models/306144/helloworld-stable-cascade-early-beta

Could an option be added to at least attempt to load a model other than the base? Or is there a simple file swap I could try to have the app load a different stage c 1b model?

Thanks!

(BTW - using this slightly modified script to play around w/ training: https://github.com/2kpr/StableCascade )

**Comment by another-ai** [comment]
The problem is than "StableCascadePriorPipeline.from_pretrained" doesn't accept .safetensors file(for now)
